---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mirror
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  volumeName: mirror
  storageClassName: ""
