---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mirror
spec:
  capacity:
    storage: 100Gi
  nfs:
    server: my.nfs.server
    path: /path/to/share
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem