---
apiVersion: v1
kind: Secret
metadata:
  name: repositories
type: Opaque
stringData:
  SOURCE: 'quay-source.example.com'
  DEST: 'destination.example.com'
  NAMESPACE: 'ocp4'
  OAUTH: 'quay_source_oauth_token'
  AUTHFILE: '/config/auth.json'
  EXTRA_ARGS: ''
