---
apiVersion: v1
kind: Secret
metadata:
  name: config
type: Opaque
stringData:
  'auth.json': |
    {
            "auths": {
                    "quay-source.example.com": {
                            "auth": "bHNoYWtlc3A...b1NYRGlHMHVJQQ=="
                    },
                    "destination.example.com'": {
                            "auth": "bHNoYWtlc36...K1g0QkdQdldwTw=="
                    }
            }
    }
